description = "Ubuntu 22.04 Jammy Jellyfish full image with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/build-jammy-full:0.1.101"

[lifecycle]
  version = "0.20.18"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/run-jammy-full:latest"

[stack]
  id = "io.buildpacks.stacks.jammy"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
