description = "Ubuntu 22.04 Jammy Jellyfish full image with no buildpacks included.sdf To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/build-jammy-full:0.1.96"

[lifecycle]
  version = "0.20.14"

[stack]
  id = "io.buildpacks.stacks.jammy"

[run]
  [[run.images]]
    image = "index.docker.io/paketobuildpacks/run-jammy-full:latest"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"